const quizInfo = {
    title: 'Can You Identify These Guitars?',
    intro: {
        image: 'https://images.unsplash.com/photo-1519508234439-4f23643125c1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1374&q=80',
        message: 'Try to figure out which guitar model is shown in the picture',
    },
    questions: [
        {
            id: 0,
            image: 'https://d1aeri3ty3izns.cloudfront.net/media/32/326049/1200/preview.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Fender Jaguar',
            answer1: 'Ibanez Talman',
            answer2: 'Fender Jaguar',
            answer3: 'Kay Vanguard',
            answer4: 'Fender Jazzmaster',
        },
        {
            id: 1,
            image: 'https://thehub.musiciansfriend.com/images/guitarsguide/gibson2018/Gibson-J45-Standard.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Gibson J-45',
            answer1: 'Gibson Hummingbird',
            answer2: 'Gibson J-200',
            answer3: 'Gibson Songwriter',
            answer4: 'Gibson J-45',
        },
        {
            id: 2,
            image: 'https://images.reverb.com/image/upload/s--mwRCLtF9--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1384829641/hcgziqa7hgkw4lwul2ch.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Gretsch Electromatic Double Jet',
            answer1: 'Gretsch Electromatic Double Jet',
            answer2: 'Gretsch Electromatic Center Block',
            answer3: 'Guild Starfire II',
            answer4: 'Danelectro 59X',
        },
        {
            id: 3,
            image: 'https://d1aeri3ty3izns.cloudfront.net/media/24/245579/1200/preview.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Martin D-18',
            answer1: 'Martin D-28',
            answer2: 'Martin D-18',
            answer3: 'Martin 000-18',
            answer4: 'Martin OM-28',
        },
        {
            id: 4,
            image: 'https://cdn.shopify.com/s/files/1/0916/0836/products/48021_Gibson_ES-175_A23737_1_ed2a60b4-7b19-42da-8fb8-46606ffc5fb6_4000x.progressive.jpg?v=1596119991',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Gibson ES-175',
            answer1: 'Gibson ES-335',
            answer2: 'Gibson ES-175',
            answer3: 'Gibson ES-339',
            answer4: 'Epiphone Casino',
        },
        {
            id: 5,
            image: 'https://images.reverb.com/image/upload/s--rcxP-2go--/f_auto,t_large/v1560256471/hytqr785kf2flq0st4qq.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'B.C. Rich Mockingbird',
            answer1: 'Dean ML 79',
            answer2: 'Dean Razorback',
            answer3: 'B.C. Rich Warlock',
            answer4: 'B.C. Rich Mockingbird',
        },
        {
            id: 6,
            image: 'https://images.reverb.com/image/upload/s--aWlg-Vug--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1522700705/aulj3vsq0kyjockv6xwa.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Rickenbacker 360/12',
            answer1: 'Rickenbacker 360/12',
            answer2: 'Rickenbacker 330',
            answer3: 'Rickenbacker 4003',
            answer4: 'Airline 2P',
        },
        {
            id: 7,
            image: 'https://www.rainbowguitars.com/imagesproduct/us/usto414cev-xl-02.jpg',
            question: 'Which famous guitar is pictured above?',
            correctAnswer: 'Taylor 414ce',
            answer1: 'Taylor 414ce',
            answer2: 'Guild OM-240',
            answer3: 'Taylor BBT',
            answer4: 'Guild Westerly',
        },
    ],
    correct: {
        image: 'https://www.colourbox.com/preview/12004600-correct.jpg',
        message: 'Correct!  Nice job',
    },
    incorrect: {
        image: 'https://www.colourbox.com/preview/12004558-incorrect.jpg',
        message: 'Wrong answer, see how you do on the next question!',
    },
    final: {
        image: 'https://images.unsplash.com/photo-1523325343676-4136d25d013b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
        message: 'Congratulations, you finished the quiz!',
    }
};

export default quizInfo;